name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-check:
    # Use the reusable build workflow for checks AND artifact generation
    uses: ./.github/workflows/build-reusable.yml
    with:
      ref: ${{ github.ref }} # Pass the ref that triggered the workflow
      upload_artifact: true # Upload artifacts for potential release workflow